# Generated by Django 4.2.2 on 2023-08-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("danie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="danie.about"
            ),
        ),
        migrations.AlterField(
            model_name="skills",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="danie.category"
            ),
        ),
    ]
